In [1]:
import numpy as np

In [2]:
dir(np) # fonksiyonlarini gormek icin 

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [2]:
print(np.__version__)

1.26.4


In [2]:
pip install --upgrade numpy # versiyon guncelleme

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 324.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.3 MB 3.2 MB/s eta 0:00:06
    --------------------------------------- 0.3/16.3 MB 3.2 MB/s eta 0:00:06
   - -------------------------------------- 0.6/16.3 MB 4.3 MB/s eta 0:00:04
   -- ------------------------------------- 0.9/16.3 MB 4.6 MB/s eta 0:00:04
   -- ------------------------------------- 1.1/16.3 MB 5.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.5/16.3 MB 5.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.7/16.3 MB 5.3 MB/s eta 0:00:03
   ---

  You can safely remove it manually.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
print(np.__doc__) # dokumanlarini gormek icin 


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

## array()

In [5]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [6]:
np.array(my_list)

array([1, 2, 3, 4])

In [8]:
np.array([1,2,3,4,5,6,7.5]) # hepsini float a cevirdi cunku arrayler tek tip veri tutar

array([1. , 2. , 3. , 4. , 5. , 6. , 7.5])

In [9]:
np.array([1,"ali",4])

array(['1', 'ali', '4'], dtype='<U11')

In [11]:
np.array([1,2,3], dtype= float)  # dtype lari degistirebiliriz 

array([1., 2., 3.])

In [13]:
np.array([1.2,3.4,4.5], dtype= int)

array([1, 3, 4])

In [17]:
np.array([[1,2],[3,4]])

array([[1, 2, 3, 4]])

In [20]:
my_list2 = [[1,2,3],[7,8,9],[10,11,12],[1,2,3]]

In [21]:
np.array(my_list2)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3]])

In [22]:
my_list3 = [[1,2,3],[7,8,9],[10,11,12],[1,2]]

In [23]:
np.array(my_list3) # sutunlar esit eleman icermeli

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [24]:
my_list4 = [   [ [  1,2,3  ],[ 4,5,6 ]   ]   ]

In [27]:
np.array(my_list4)

array([[[1, 2, 3],
        [4, 5, 6]]])

### shape() & reshape()

In [28]:
my_arr = np.array(my_list2)

In [29]:
my_arr.shape # 2 boyutlu

(4, 3)

In [30]:
np.array([1,2,3]).shape # tek boyutlu

(3,)

In [31]:
np.array(my_list4).shape # 3 boyutlu

(1, 2, 3)

In [32]:
my_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  7],
       [ 8,  9],
       [10, 11],
       [12,  1],
       [ 2,  3]])

In [35]:
my_arr.reshape(3,5) #cannot reshape array of size 12 into shape (3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [36]:
my_arr.reshape(3,3) # cannot reshape array of size 12 into shape (3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [37]:
my_arr.reshape(3,-1) # 3 tane satir olsun kac tane sutun gerekiyorsa o kendi olustursun 

array([[ 1,  2,  3,  7],
       [ 8,  9, 10, 11],
       [12,  1,  2,  3]])

In [38]:
my_arr.reshape(-1,4)

array([[ 1,  2,  3,  7],
       [ 8,  9, 10, 11],
       [12,  1,  2,  3]])

## ndim & ndmin

In [ ]:
my_list2 = [[1,2,3],[7,8,9],[10,11,12],[1,2,3]]

In [39]:
my_arr = np.array(my_list2)
my_arr

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3]])

In [40]:
my_arr.ndim # ndim bir arrayin kac boyutlu olduunu gosterir

2

In [41]:
np.array([1,2,3]).ndim

1

In [42]:
lii = [[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]

In [43]:
np.array(lii).ndim

3